repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.2
  hooks:
    - id: terraform_fmt    
    - id: terraform_docs
    # - id: terraform_validate
    - id: terraform_tflint
      args:
        - --minimum-failure-severity=notice --recursive --config
