pack:
  spectrocloud.com/install-priority: "10"
manifests:
  byo-manifest:
    contents: |
      
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: hipster
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://github.com/3pings/microservices-demo.git
          targetRevision: ${branch}
          path: release
        destination:
          server: https://kubernetes.default.svc
          namespace: hipster
        syncPolicy:
            automated: {}
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: hipster