manifests:
  metallb:

    #The namespace to use for deploying MetalLB
    namespace: "metallb-system"

    #MetalLB will skip setting .0 & .255 IP address when this flag is enabled
    avoidBuggyIps: true

    # Layer 2 config; The IP address range MetalLB should use while assigning IP's for svc type LoadBalancer
    # For the supported formats, check https://metallb.universe.tf/configuration/#layer-2-configuration
    addresses:
    - "${metalLb_range}"